version: "3.8"

services:
  db-app:
    image: postgres
    restart: always
    env_file: ./database/.env
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
      # - ./database/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pdadmin-app:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    env_file: ./database/.env
    depends_on:
      - db-app

  server-app:
    build: ./backend
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    env_file: ./backend/.env
    depends_on:
      - db-app
